# themester_managed = "Theme: Catppuccin Latte"

[colors.bright]
black = "#6c6f85"
blue = "#1e66f5"
cyan = "#179299"
green = "#40a02b"
magenta = "#ea76cb"
red = "#d20f39"
white = "#6c6f85"
yellow = "#df8e1d"

[colors.cursor]
cursor = "#dc8a78"
text = "#eff1f5"

[colors.footer_bar]
background = "#6c6f85"
foreground = "#eff1f5"

[colors.hints.end]
background = "#6c6f85"
foreground = "#eff1f5"

[colors.hints.start]
background = "#df8e1d"
foreground = "#eff1f5"

[[colors.indexed_colors]]
color = "#fe640b"
index = 16

[[colors.indexed_colors]]
color = "#dc8a78"
index = 17

[colors.normal]
black = "#5c5f77"
blue = "#1e66f5"
cyan = "#179299"
green = "#40a02b"
magenta = "#ea76cb"
red = "#d20f39"
white = "#5c5f77"
yellow = "#df8e1d"

[colors.primary]
background = "#eff1f5"
bright_foreground = "#4c4f69"
dim_foreground = "#6c6f85"
foreground = "#4c4f69"

[colors.search.focused_match]
background = "#40a02b"
foreground = "#eff1f5"

[colors.search.matches]
background = "#6c6f85"
foreground = "#eff1f5"

[colors.selection]
background = "#dc8a78"
text = "#eff1f5"

[colors.vi_mode_cursor]
cursor = "#7287fd"
text = "#eff1f5"

[env]
TERM = "xterm-256color"

[font]
size = 11.5

[font.normal]
family = "0xProto Nerd Font Mono"
style = "Regular"

[general]
import = ["~/.config/alacritty/catppuccin-latte.toml"]

[[keyboard.bindings]]
action = "ToggleFullscreen"
key = "Return"
mods = "Super"

[window]
decorations = "none"
