# themester_managed = "Theme: Catppuccin Mocha"

[colors.bright]
black = "#6c7086"
blue = "#89b4fa"
cyan = "#94e2d5"
green = "#a6e3a1"
magenta = "#f5c2e7"
red = "#f38ba8"
white = "#a6adc8"
yellow = "#f9e2af"

[colors.cursor]
cursor = "#f5e0dc"
text = "#1e1e2e"

[colors.footer_bar]
background = "#a6adc8"
foreground = "#1e1e2e"

[colors.hints.end]
background = "#a6adc8"
foreground = "#1e1e2e"

[colors.hints.start]
background = "#f9e2af"
foreground = "#1e1e2e"

[[colors.indexed_colors]]
color = "#fab387"
index = 16

[[colors.indexed_colors]]
color = "#f2cdcd"
index = 17

[colors.normal]
black = "#585b70"
blue = "#89b4fa"
cyan = "#94e2d5"
green = "#a6e3a1"
magenta = "#f5c2e7"
red = "#f38ba8"
white = "#bac2de"
yellow = "#f9e2af"

[colors.primary]
background = "#1e1e2e"
bright_foreground = "#cdd6f4"
dim_foreground = "#9399b2"
foreground = "#cdd6f4"

[colors.search.focused_match]
background = "#a6e3a1"
foreground = "#1e1e2e"

[colors.search.matches]
background = "#a6adc8"
foreground = "#1e1e2e"

[colors.selection]
background = "#f5e0dc"
text = "#1e1e2e"

[colors.vi_mode_cursor]
cursor = "#b4befe"
text = "#1e1e2e"

[env]
TERM = "xterm-256color"

[font]
size = 11.5

[font.normal]
family = "0xProto Nerd Font Mono"
style = "Regular"

[general]
import = ["~/.config/alacritty/catppuccin-latte.toml"]

[[keyboard.bindings]]
action = "ToggleFullscreen"
key = "Return"
mods = "Super"

[window]
decorations = "none"
