[runtime]
reactive_tests = true
std_stream_max_bytes = 1000000
watcher_on_save = "lazy"
auto_reload = "off"
on_cell_change = "autorun"
auto_instantiate = true
output_max_bytes = 8000000
default_sql_output = "auto"

[ai]
rules = ""

[ai.anthropic]

[ai.open_ai]

[ai.bedrock]

[ai.google]

[formatting]
line_length = 80

[package_management]
manager = "uv"

[language_servers.pylsp]
enable_ruff = true
enable_pyflakes = false
enable_mypy = true
enable_flake8 = false
enable_pydocstyle = false
enabled = true
enable_pylint = false

[experimental]

[server]
follow_symlink = false
browser = "default"

[diagnostics]

[snippets]
custom_paths = []
include_default_snippets = true

[display]
theme = "dark"
cell_output = "below"
default_width = "medium"
code_editor_font_size = 14
dataframes = "rich"
default_table_page_size = 100

[keymap]
preset = "vim"

[keymap.overrides]

[save]
format_on_save = false
autosave = "after_delay"
autosave_delay = 1000

[completion]
activate_on_typing = true
copilot = false
