[runtime]
auto_reload = "off"
reactive_tests = true
auto_instantiate = true
output_max_bytes = 8000000
on_cell_change = "autorun"
watcher_on_save = "lazy"
std_stream_max_bytes = 1000000
default_sql_output = "auto"

[diagnostics]

[keymap]
preset = "vim"

[keymap.overrides]

[formatting]
line_length = 79

[experimental]

[completion]
copilot = false
activate_on_typing = true

[display]
cell_output = "above"
default_table_page_size = 100
default_width = "medium"
dataframes = "rich"
code_editor_font_size = 14
theme = "system"

[snippets]
include_default_snippets = true
custom_paths = []

[ai]
rules = ""
[ai.google]

[ai.open_ai]

[ai.bedrock]

[ai.anthropic]

[language_servers.pylsp]
enabled = true
enable_pydocstyle = false
enable_ruff = true
enable_pylint = false
enable_mypy = true
enable_flake8 = false
enable_pyflakes = false

[package_management]
manager = "uv"

[server]
browser = "default"
follow_symlink = false

[save]
autosave = "after_delay"
autosave_delay = 1000
format_on_save = false
