[package_management]
manager = "uv"

[experimental]

[completion]
copilot = false
activate_on_typing = true

[display]
default_width = "medium"
reference_highlighting = false
theme = "system"
cell_output = "below"
default_table_max_columns = 50
dataframes = "rich"
code_editor_font_size = 14
default_table_page_size = 100

[ai]
rules = ""
mode = "manual"

[ai.bedrock]

[ai.google]

[ai.open_ai]

[ai.anthropic]

[keymap]
destructive_delete = true
preset = "vim"

[keymap.overrides]

[snippets]
include_default_snippets = true
custom_paths = []

[save]
autosave_delay = 1000
autosave = "after_delay"
format_on_save = false

[server]
browser = "default"
follow_symlink = false

[formatting]
line_length = 79

[language_servers.pylsp]
enable_mypy = true
enable_pydocstyle = false
enable_pylint = false
enable_pyflakes = false
enable_ruff = true
enable_flake8 = false
enabled = true

[runtime]
on_cell_change = "autorun"
auto_reload = "lazy"
output_max_bytes = 8000000
watcher_on_save = "lazy"
default_sql_output = "auto"
auto_instantiate = true
reactive_tests = true
default_auto_download = []
std_stream_max_bytes = 1000000
