[save]
autosave_delay = 1000
autosave = "after_delay"
format_on_save = false

[runtime]
default_sql_output = "auto"
output_max_bytes = 8000000
auto_instantiate = true
std_stream_max_bytes = 1000000
watcher_on_save = "lazy"
reactive_tests = true
on_cell_change = "autorun"
auto_reload = "off"

[diagnostics]

[display]
code_editor_font_size = 14
cell_output = "above"
dataframes = "rich"
theme = "system"
default_width = "medium"
default_table_page_size = 10

[package_management]
manager = "uv"

[experimental]

[keymap]
preset = "vim"

[keymap.overrides]

[formatting]
line_length = 79

[language_servers.pylsp]
enable_ruff = true
enable_mypy = true
enabled = true
enable_flake8 = false
enable_pydocstyle = false
enable_pylint = false
enable_pyflakes = false

[snippets]
include_default_snippets = true
custom_paths = []

[ai]
rules = ""
[ai.bedrock]

[ai.open_ai]

[ai.anthropic]

[ai.google]

[server]
browser = "default"
follow_symlink = false

[completion]
copilot = false
activate_on_typing = true
