[formatting]
line_length = 79

[snippets]
custom_paths = []
include_default_snippets = true

[server]
follow_symlink = false
browser = "default"

[package_management]
manager = "uv"

[ai]
rules = ""

[ai.open_ai]

[ai.anthropic]

[ai.bedrock]

[ai.google]

[experimental]

[language_servers.pylsp]
enable_mypy = true
enable_pyflakes = false
enabled = true
enable_pylint = false
enable_pydocstyle = false
enable_ruff = true
enable_flake8 = false

[display]
default_width = "medium"
default_table_page_size = 100
theme = "system"
code_editor_font_size = 14
dataframes = "rich"
cell_output = "below"

[save]
format_on_save = false
autosave_delay = 1000
autosave = "after_delay"

[completion]
activate_on_typing = true
copilot = false

[runtime]
output_max_bytes = 8000000
watcher_on_save = "lazy"
on_cell_change = "autorun"
std_stream_max_bytes = 1000000
reactive_tests = true
auto_instantiate = true
auto_reload = "off"
default_sql_output = "auto"

[keymap]
preset = "vim"

[keymap.overrides]

[diagnostics]
